### ISSUE TITLE
Pipe symbol not allowed in inline images

### ISSUE THREAD

**Issue by AlastairTaft** [wooorm/remark#164]
This may be by design but I just ran into the issue. I'm wondering if I need to change the image url before hand or if it should be handling it okay. The issue only occurs when the `|` character exists in the url.

The below markdown barfs with the following stack trace.

```
![](https://mybrandsitetest.s3.amazonaws.com/google-oauth2|106904007808659933435/penguinlowres.png)
```

```
TypeError: Cannot read property 'length' of undefined
    at Of.tokenizeTable (/Users/alastairtaft/projects/mybrand-web/node_modules/remark/lib/parse.js:3048:24)
    at Of.tokenize (/Users/alastairtaft/projects/mybrand-web/node_modules/remark/lib/parse.js:5969:28)
    at Of.renderBlock (/Users/alastairtaft/projects/mybrand-web/node_modules/remark/lib/parse.js:3808:41)
    at Of.Parser.parse (/Users/alastairtaft/projects/mybrand-web/node_modules/remark/lib/parse.js:5499:17)
    at Processor.parse (/Users/alastairtaft/projects/mybrand-web/node_modules/unified/index.js:179:69)
    at Ware.<anonymous> (/Users/alastairtaft/projects/mybrand-web/node_modules/unified/index.js:30:32)
    at Ware.<anonymous> (/Users/alastairtaft/projects/mybrand-web/node_modules/wrap-fn/index.js:75:16)
    at Ware.<anonymous> (/Users/alastairtaft/projects/mybrand-web/node_modules/wrap-fn/index.js:57:27)
    at next (/Users/alastairtaft/projects/mybrand-web/node_modules/ware/lib/index.js:85:20)
    at Ware.run (/Users/alastairtaft/projects/mybrand-web/node_modules/ware/lib/index.js:88:3)
    at Processor.process (/Users/alastairtaft/projects/mybrand-web/node_modules/unified/index.js:250:18)
```

**Comment by wooorm** [comment]
I cannot reproduce. Pipes should be allowed in remark though!

* What version of remark are you using? (tip: `npm ls --depth=0`);
* What configuration are you using, e.g., do you use `.remarkrc` files or `package.json` files and what do they contains;
* What command or code do you use to execute remark?

Thanks

**Comment by AlastairTaft** [comment]
I just checked my version and saw it was out of date, I was on 3.2.3 but I've just updated to 4.1.0 and receive a very similar stack trace, I've updated my original post with the new stack trace.

I can reproduce the error running the following file with node. 

```
var remark = require('remark')
var processor = remark()

processor.process('![](https://mybrandsitetest.s3.amazonaws.com/google-oauth2|106904007808659933435/penguinlowres.png)')
```


I'm not using a `.remarkrc` file. And my `package.json` file contains remark@4.1.0



```
{
  "dependencies": {
    ...
    "remark": "^4.1.0",
    "remark-react": "^1.1.0",
  }
}

**Comment by wooorm** [comment]
Found it! Thanks for reporting, will have a fix out soon.

**Comment by AlastairTaft** [comment]
Awesome!

**Comment by wooorm** [comment]
Deployed!
