### ISSUE TITLE
remark cli don't seem to work from subdirectories

### ISSUE THREAD

**Issue by kahwee** [wooorm/remark#165]
Hi

Reference repository https://github.com/kahwee/remark-test3

I'm not sure why remark CLI doesn't work from subdirectories. I only have one plugin `remark-html` and if you execute it from the `tools` directory, it doesn't work.

```sh
cd tools
npm run build-subdir
```

It does work from the root directory though. 

Is this by design? We have a slightly odd directory structure in https://github.com/nodejs/node that the tools have to live in `tools/doc` and I'm hoping to be able to transfer all the code into a plugin.

Thanks.

**Comment by wooorm** [comment]
I cloned your project, CDed into it, and ran `npm run build-root`, that failed.

#### `build-root`

```sh
🚀  remark-test3 master [?]: npm run build-root

> remark3@1.0.0 build-root /Users/tilde/projects/oss/remark-test3
> remark docs --output out/docs

# Hello

Hidocs/test.md
        1:1  error    Error: Cannot find module 'html'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at findPlugin (/Users/tilde/projects/oss/remark/lib/cli/file-pipeline/configure.js:138:12)
    at /Users/tilde/projects/oss/remark/lib/cli/file-pipeline/configure.js:205:26
    at handleLocalConfiguration (/Users/tilde/projects/oss/remark/lib/cli/configuration.js:294:9)
    at /Users/tilde/projects/oss/remark/lib/cli/configuration.js:211:9
    at /Users/tilde/projects/oss/remark/node_modules/vfile-find-up/index.js:207:17
    at FSReqWrap.oncomplete (fs.js:82:15)

✖ 1 error
```

Still from the root, I executed:

```sh
🚀  remark-test3 master [?]: npm install remark-html -S

remark3@1.0.0 /Users/tilde/projects/oss/remark-test3
└─┬ remark-html@3.0.0 
  ├── collapse-white-space@1.0.0 
  ├─┬ detab@1.0.2 
  │ └── repeat-string@1.5.2 
  ├── normalize-uri@1.0.0 
  ├── object-assign@4.0.1 
  ├── trim@0.0.1 
  ├── trim-lines@1.0.0 
  └── unist-util-visit@1.0.1 

npm WARN remark3@1.0.0 No repository field.
```

Then, re-running `build-root`:

```sh
🚀  remark-test3 master [!?]: npm run build-root

> remark3@1.0.0 build-root /Users/tilde/projects/oss/remark-test3
> remark docs --output out/docs

docs/test.md > out/docs/test.html: written
🚀  remark-test3 master [!?]: cat out/docs/test.html 
<h1>Hello</h1>
<p>Hi</p>
```

#### `build-subdir`

Okay, first removing the previously added stuff:

```sh
git reset HEAD
git checkout -- .
rm out/docs/test.html
```

...and we’re back to normal.

Now, executing the code which failed for you:

```sh
🚀  remark-test3 master: cd tools
🚀  tools master: npm install
npm WARN tools@1.0.0 No description
npm WARN tools@1.0.0 No repository field.
🚀  tools master: npm run build-subdir

> tools@1.0.0 build-subdir /Users/tilde/projects/oss/remark-test3/tools
> remark ../docs --output ../out/docs

../docs/test.md > ../out/docs/test.html: written
🚀  tools master: cat ../out/docs/test.html 
<h1>Hello</h1>
<p>Hi</p>
```

...stuff works!

#### Tips

Okay, so for me everything works fine.

Can you:

* let me know what version of `remark` you have installed globally?
* Tell me whether or not you have `remark-html` installed globally?
* Provide actual examples of your input and output. Tip: run `remark` with debug mode on: [`DEBUG="*" remark`](https://github.com/wooorm/remark/blob/master/doc/remark.1.md#description).

**Comment by kahwee** [comment]
Thanks for your diagnosis. I found out to reproduce this better. Can you pull this again? https://github.com/kahwee/remark-test3

This time, ignore the root directory and go into `tools`. I renamed the `.remarkrc` in the root directory to `.remarkrcdisabled`.

In global
* Installed `remark` in global is 4.1.1 only.

I forgot to add `remark` and `remark-html` in the package.json of the root.

I turned on the debug flag. Tried building on the sub directory `tools`.

```remark3 - master ❯ cd tools
tools - master ❯ npm run build-subdir

> tools@1.0.0 build-subdir /home/kahwee/projects/remark3/tools
> remark ../docs --output ../out/docs

  remark:cli:ignore Constructing ignore for `/home/kahwee/projects/remark3/tools` +0ms
  remark:cli:file-set-pipeline:stdin Checking stdin +15ms
  remark:cli:file-set-pipeline:stdin Ignoring stdin +1ms
  remark:cli:file-pipeline:read Reading `../docs/test-2.md` in `utf-8` +1ms
  remark:cli:file-pipeline:read Reading `../docs/test.md` in `utf-8` +0ms
  remark:cli:file-pipeline:read Read `../docs/test-2.md` (err: null) +2ms
  remark:cli:configuration Constructing configuration for `../docs/test-2.md` +1ms
  remark:cli:file-pipeline:read Read `../docs/test.md` (err: null) +1ms
  remark:cli:configuration Constructing configuration for `../docs/test.md` +0ms
  remark:cli:configuration Using /home/kahwee/projects/remark3/package.json +6ms
  remark:cli:file-pipeline:configure Setting output `../out/docs` +1ms
  remark:cli:file-pipeline:configure Using settings `{"position":true,"gfm":true,"yaml":true,"commonmark":false,"footnotes":false,"pedantic":false,"breaks":false,"entities":"false","setext":false,"closeAtx":false,"looseTable":false,"spacedTable":true,"incrementListMarker":true,"fences":false,"fence":"`","bullet":"-","listItemIndent":"tab","rule":"*","ruleSpaces":true,"ruleRepetition":3,"strong":"*","emphasis":"_"}` +0ms
  remark:cli:file-pipeline:configure Using plug-ins `[]` +0ms
  remark:cli:file-pipeline:configure Using `0` injected plugins +0ms
  remark:cli:file-pipeline:parse Parsing document +0ms
  remark:cli:file-pipeline:parse Parsed document +9ms
  remark:cli:file-pipeline:transform Transforming document +0ms ../docs/test-2.md
  remark:cli:file-pipeline:transform Transformed document (error: null) +0ms
  remark:cli:file-pipeline:queue Queueing ../docs/test-2.md +0ms
  remark:cli:file-pipeline:queue Can flush for `../docs/test-2.md` +0ms
  remark:cli:file-pipeline:queue Interupting flush as ../docs/test.md is not finished +0ms
  remark:cli:file-pipeline:queue Not flushing +0ms
  remark:cli:configuration Using /home/kahwee/projects/remark3/package.json +1ms
  remark:cli:file-pipeline:configure Setting output `../out/docs` +0ms
  remark:cli:file-pipeline:configure Using settings `{"position":true,"gfm":true,"yaml":true,"commonmark":false,"footnotes":false,"pedantic":false,"breaks":false,"entities":"false","setext":false,"closeAtx":false,"looseTable":false,"spacedTable":true,"incrementListMarker":true,"fences":false,"fence":"`","bullet":"-","listItemIndent":"tab","rule":"*","ruleSpaces":true,"ruleRepetition":3,"strong":"*","emphasis":"_"}` +0ms
  remark:cli:file-pipeline:configure Using plug-ins `[]` +0ms
  remark:cli:file-pipeline:configure Using `0` injected plugins +0ms
  remark:cli:file-pipeline:parse Parsing document +0ms
  remark:cli:file-pipeline:parse Parsed document +1ms
  remark:cli:file-pipeline:transform Transforming document +0ms ../docs/test.md
  remark:cli:file-pipeline:transform Transformed document (error: null) +0ms
  remark:cli:file-pipeline:queue Queueing ../docs/test.md +0ms
  remark:cli:file-pipeline:queue Can flush for `../docs/test-2.md` +0ms
  remark:cli:file-pipeline:queue Can flush for `../docs/test.md` +0ms
  remark:cli:file-pipeline:queue Flushing +0ms
  remark:cli:file-pipeline:stringify Compiling document +0ms
  remark:cli:file-pipeline:stringify Compiled document to md +2ms
  remark:cli:file-pipeline:copy Copying `../docs/test-2.md` +0ms
  remark:cli:file-pipeline:copy Copying document from ../docs/test-2.md to ../out/docs/test-2.md +0ms
  remark:cli:file-pipeline:stdout Ignoring writing to standard out +0ms
  remark:cli:file-pipeline:file-system Writing document to `../out/docs/test-2.md` +0ms
  remark:cli:file-pipeline:stringify Compiling document +1ms
  remark:cli:file-pipeline:stringify Compiled document to md +0ms
  remark:cli:file-pipeline:copy Copying `../docs/test.md` +0ms
  remark:cli:file-pipeline:copy Copying document from ../docs/test.md to ../out/docs/test.md +0ms
  remark:cli:file-pipeline:stdout Ignoring writing to standard out +0ms
  remark:cli:file-pipeline:file-system Writing document to `../out/docs/test.md` +0ms
../docs/test-2.md > ../out/docs/test-2.md: written
../docs/test.md > ../out/docs/test.md: written
```

I notice it is using `/home/kahwee/projects/remark3/package.json` (root directory) instead of `/home/kahwee/projects/remark3/tools/package.json` (sub directory). Could this be the reason?

I am running on Ubuntu 15.10. I'll be trying on Mac OS X when I get into the office to see if it's the same results.

**Comment by wooorm** [comment]
Ah, now I understand your problem.

This indeed doesn’t work. By design. Because, files are what originates the search, not the CWD.
`.remarkrc` files must be adjacent or above those files. Read more about it the [“CASCADE” section of the `.remarkrc` docs](https://github.com/wooorm/remark/blob/master/doc/remarkrc.5.md#cascade).

If you want to overwrite this behaviour, provide `-c, --config-path <path>` to the CLI.

For example, with your code (and appropriate `npm install`s) and these changes:

```diff
diff --git a/tools/package.json b/tools/package.json
index aa75c5b..ced484e 100644
--- a/tools/package.json
+++ b/tools/package.json
@@ -4,7 +4,7 @@
   "description": "",
   "main": "index.js",
   "scripts": {
-    "build-subdir": "remark ../docs --output ../out/docs",
+    "build-subdir": "remark -c .remarkrc ../docs --output ../out/docs",
     "test": "echo \"Error: no test specified\" && exit 1"
   },
   "author": "",
```

and the following code:

```sh
🚀  remark-test3 master [!]: cd tools
🚀  tools master [!]: npm run build-subdir
```

Yields:

```
> tools@1.0.0 build-subdir /Users/tilde/projects/oss/remark-test3/tools
> remark -c .remarkrc ../docs --output ../out/docs

../docs/test-2.md > ../out/docs/test-2.html: written
../docs/test.md > ../out/docs/test.html: written
```

**Comment by kahwee** [comment]
I get it now. Thanks @wooorm!
