### ISSUE TITLE
Error using lint plugin: "Cannot find module 'lint'"

### ISSUE THREAD

**Issue by jtpalmer** [wooorm/remark#166]
I'm seeing the same error as #131 

Here is the debugging information you requested:

```
$ remark -V
4.1.1

$ cat .remarkrc 
{
  "plugins": {
    "lint": {
      "no-html": false
    }
  }
}

$ cat example.md 
Alpha bravo charlie delta echo foxtrot golf hotel india Juliet kilo lima mike November this line is too long.

<span></span>

```

```
$ DEBUG="*" remark example.md
  remark:cli:ignore Constructing ignore for `/tmp` +0ms
  remark:cli:file-set-pipeline:stdin Checking stdin +7ms
  remark:cli:file-set-pipeline:stdin Ignoring stdin +0ms
  remark:cli:file-pipeline:read Reading `example.md` in `utf-8` +1ms
  remark:cli:file-pipeline:read Read `example.md` (err: null) +0ms
  remark:cli:configuration Constructing configuration for `example.md` +1ms
  remark:cli:configuration Using /tmp/.remarkrc +2ms
  remark:cli:file-pipeline:configure Setting output `undefined` +0ms
  remark:cli:file-pipeline:configure Using settings `{"position":true,"gfm":true,"yaml":true,"commonmark":false,"footnotes":false,"pedantic":false,"breaks":false,"entities":"false","setext":false,"closeAtx":false,"looseTable":false,"spacedTable":true,"incrementListMarker":true,"fences":false,"fence":"`","bullet":"-","listItemIndent":"tab","rule":"*","ruleSpaces":true,"ruleRepetition":3,"strong":"*","emphasis":"_"}` +0ms
  remark:cli:file-pipeline:configure Using plug-ins `["lint"]` +0ms
  remark:cli:file-pipeline:configure Using plug-in `lint` at `lint` +0ms
  remark:cli:file-pipeline:queue Queueing example.md +3ms
  remark:cli:file-pipeline:queue Flushing +0ms
  remark:cli:file-pipeline:stringify Not compiling failed document +0ms
  remark:cli:file-pipeline:copy Not copying +0ms
  remark:cli:file-pipeline:stdout Writing document to standard out +0ms
Alpha bravo charlie delta echo foxtrot golf hotel india Juliet kilo lima mike November this line is too long.

<span></span>

  remark:cli:file-pipeline:file-system Ignoring writing to file-system +0ms
example.md
        1:1  error    Error: Cannot find module 'lint'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at findPlugin (/home/jtpalmer/.npm-packages/lib/node_modules/remark/lib/cli/file-pipeline/configure.js:138:12)
    at /home/jtpalmer/.npm-packages/lib/node_modules/remark/lib/cli/file-pipeline/configure.js:205:26
    at handleLocalConfiguration (/home/jtpalmer/.npm-packages/lib/node_modules/remark/lib/cli/configuration.js:294:9)
    at /home/jtpalmer/.npm-packages/lib/node_modules/remark/lib/cli/configuration.js:211:9
    at /home/jtpalmer/.npm-packages/lib/node_modules/remark/node_modules/vfile-find-up/index.js:207:17
    at Object.oncomplete (fs.js:107:15)

✖ 1 error
```

```
$ node -v
v0.10.25
```

```
$ npm -v
1.3.10
```

These are the node and npm version packaged for Ubuntu 14.04.4 LTS.

It may also be worth noting that I've set my prefix to `${HOME}/.npm-packages` in my `.npmrc` file.

I don't have a `node_modules` directory in this example, but here is what's in my prerfx:

```
$ ls -la ~/.npm-packages/lib/node_modules/
total 44
drwxrwxr-x 11 jtpalmer jtpalmer 4096 Feb 23 11:45 .
drwxrwxr-x  3 jtpalmer jtpalmer 4096 May 22  2015 ..
drwxrwxr-x  7 jtpalmer jtpalmer 4096 Jan 20 08:24 browserify
drwxrwxr-x  5 jtpalmer jtpalmer 4096 Jan 26 14:09 js-beautify
drwxrwxr-x  7 jtpalmer jtpalmer 4096 Jan 19 10:44 jscs
drwxrwxr-x  7 jtpalmer jtpalmer 4096 Jan 20 08:24 jshint
drwxrwxr-x  7 jtpalmer jtpalmer 4096 Jan 20 08:24 jslint
drwxrwxr-x  6 jtpalmer jtpalmer 4096 Nov  5 07:23 marked
drwxrwxr-x  6 jtpalmer jtpalmer 4096 Feb 23 11:41 remark
drwxrwxr-x  4 jtpalmer jtpalmer 4096 Feb 23 11:45 remark-lint
drwxrwxr-x  6 jtpalmer jtpalmer 4096 Jan 20 08:24 watchify
```

I can delete everything and reinstall only remark if that would be helpful.

Thank you, let me know if there is any other information I can provide.

**Comment by wooorm** [comment]
Thanks for trying remark!

I think this has to do with the non-standard prefix. Pinging @eush77 as he created the code for that. Eugene: would it be possible to support non-standard prefixes?

A quick fix would be to install `remar-lint` locally (without the `-g` flag). Would that be possible?

**Comment by jtpalmer** [comment]
Installing `remark-lint` locally fixes the problem for me.  I can do that for now.  Thanks.

**Comment by eush77** [comment]
The problem was that [npm-prefix](https://github.com/eush77/npm-prefix) didn't interpret environment variables in npm prefix config. This is fixed now in npm-prefix@1.2.0, reinstalling remark's dependencies should grab that version.

@jtpalmer Could you reinstall remark and confirm that the problem is gone?

**Comment by jtpalmer** [comment]
Thanks @eush77 , that fixed the problem.

**Comment by wooorm** [comment]
Thanks you both for the time!
