### ISSUE TITLE
"sudo npm install -g remark" command fails

### ISSUE THREAD

**Issue by cmcginty** [wooorm/remark#173]
I'm getting some interesting results trying to install remark
```
npm http GET https://registry.npmjs.org/remark
npm http 304 https://registry.npmjs.org/remark
npm http GET https://registry.npmjs.org/camelcase
npm http GET https://registry.npmjs.org/ccount
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/chokidar
npm http GET https://registry.npmjs.org/to-vfile
npm http GET https://registry.npmjs.org/collapse-white-space
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/concat-stream
npm http GET https://registry.npmjs.org/vfile-reporter
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/elegant-spinner
npm http GET https://registry.npmjs.org/globby
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/log-update
npm http GET https://registry.npmjs.org/longest-streak
npm http GET https://registry.npmjs.org/markdown-table
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/npm-prefix
npm http GET https://registry.npmjs.org/repeat-string
npm http GET https://registry.npmjs.org/parse-entities
npm http GET https://registry.npmjs.org/stringify-entities
npm http GET https://registry.npmjs.org/trim
npm http GET https://registry.npmjs.org/trim-trailing-lines
npm http GET https://registry.npmjs.org/unified
npm http GET https://registry.npmjs.org/unist-util-remove-position
npm http GET https://registry.npmjs.org/user-home
npm http GET https://registry.npmjs.org/vfile-find-down
npm http GET https://registry.npmjs.org/vfile
npm http GET https://registry.npmjs.org/vfile-find-up
npm http GET https://registry.npmjs.org/vfile-location
npm http GET https://registry.npmjs.org/ware
npm http 304 https://registry.npmjs.org/camelcase
npm http 200 https://registry.npmjs.org/to-vfile
npm ERR! registry error parsing json
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/ccount
npm http 304 https://registry.npmjs.org/chokidar
npm http 304 https://registry.npmjs.org/collapse-white-space
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/concat-stream
npm http 200 https://registry.npmjs.org/vfile-reporter
npm ERR! registry error parsing json
npm http 304 https://registry.npmjs.org/debug
npm ERR! SyntaxError: Unexpected token ^_
npm ERR! ^_^@^@^@^@^@^D^C�X�n�F^V���^L<U+0516> R^Oˉ�E�f�^T͢-�u�^B�^]iH^N���^Y-g(�k^X؏؟���O����^Y�zĉ�l^V�^A^BSw��q��w��LZ����:��hu[�B�A^Y^D���8^Y�<^]��a�?8I�h0JN���^S1��'�U<^W�҉0q!WVj���Bp+^XgN9K^K��^G^Y
npm ERR! V�.�!��^F�/Lkr���l,^Y^O�a�u�m�Ea�ʝz"�<U+07B7>Z�5���^G��d,��`~x�^Z~]��$0<m�eaK��Z�Ȋw^V�V���1R-��:��ͅxI���J���p��LOZo�0s.)]^R\��+^CuQ�o�(@�d<U+052B>���H�s^LG`m�`�^P+m���-��ޮ(��$o�"���ڕ��z�-�(�u<U+07BB>�Z^W��^F�#���K^M^G�|���4�g�¯nK�i
npm ERR! +%í^CW^L"MQ��:,^QS���d�ɞ�^B�   q�����兂^T^PΩj*⎉�ө^Q��a�0�^Y��^Z{�G^@�T^Wl^Z�x�X��^W���R�kE|�^Y5�.|�/+���6�n^Eޜ^�^���2�^R6MJ�X�sՃ^G^Ka-.1^A"^@Z'd��9�U��^Oϻ�^L�R���{=�L��^M�uRf�˦�"S^E�B"�<��^E6���^GO=z�CJ�<U+05EC>��Q[1A�*�^N^\*^Z�h
npm ERR! �Dtmv^GA������]������@��L��^^\9^Y�^P�EO^O{^Y(D:AZS�[�^E��q�^R�Ņr1y���x��R���^D!�^]��<�^\�g����l�cd��C�v^Y�N�Y�^K�^K�y������9^PY �^N�
npm ERR! ^?��Κy3=�^Q^^��.Y^A^Rq+��ql���^Q��@��
npm ERR! �C�\T�ʷ�?v��ȼ�8����^Q�^C       ��^B�Q�a���z��h߸&t��
npm ERR! /p�x\�'�ar�zs��^X��v:��^_^K
npm ERR! P��D!�p�1m^M_-Ӯ�^�^BӅ��^Wr���^\K^U�5o�_��OFD8���#�挌�[ �
npm ERR! �;,_�.�^A�r=���U�^YU���<U+077E>���^Z�6
npm ERR! ^Yr�C�"�ˎ��:�.^PL�ߟ(^Gm^PΘ��^Foi�S�A��^Fڠ^O^@���=��^]��8^Uc�EX+��$�^B����@�B�鼁(J��)�[���>^L�^P^H���~W|ޢ^]l�r�^Q*�Y�&W�^O�o^M�N���Ѐ\UfY{�.�^]��Bg]�&���G�s��SYu�{�^W^Z�}��V^_��|�٨$���^X��^_lY^G�u�|��e�^BRj�^@m�^?�Х�n��^O��^N�+�g��
npm ERR! �t��,�E�T�b���T<U+0518>S|��<���ً^_�_�ٿ�Ŧ��g�k��-�^S��xi��߉����;|�Hd*^E��^N�u0菃���`<^Y^N&}|��^B{1b<U+009D>��L�-�#z>�E�s~��^?��^V���������-^W�V^W^L��^Sp��7on-��<U+10133E>H���^F^S�vw+^V^@^@
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
 npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-38-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "remark"
npm ERR! cwd /home/pcm/dotfiles/vim
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type unexpected_token
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/globby
npm http 304 https://registry.npmjs.org/longest-streak
npm http 304 https://registry.npmjs.org/log-update
npm http 304 https://registry.npmjs.org/markdown-table
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/parse-entities
npm http 304 https://registry.npmjs.org/repeat-string
npm http 304 https://registry.npmjs.org/npm-prefix
npm http 304 https://registry.npmjs.org/stringify-entities
npm http 304 https://registry.npmjs.org/trim
npm http 304 https://registry.npmjs.org/trim-trailing-lines
npm http 304 https://registry.npmjs.org/unified
npm http 304 https://registry.npmjs.org/unist-util-remove-position
npm http 304 https://registry.npmjs.org/user-home
npm http 304 https://registry.npmjs.org/vfile-find-down
npm http 304 https://registry.npmjs.org/vfile
npm http 304 https://registry.npmjs.org/vfile-find-up
npm http 304 https://registry.npmjs.org/vfile-location
npm http 304 https://registry.npmjs.org/ware
npm http 304 https://registry.npmjs.org/camelcase
npm http 304 https://registry.npmjs.org/ccount
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pcm/dotfiles/vim/npm-debug.log
npm ERR! not ok code 0
```

**Comment by wooorm** [comment]
Outside of the scope of this project; please fill with npm, as the log says.

P.s. Im guessing updating npm and node might help!

**Comment by cmcginty** [comment]
Thanks, I found a related issue on NPM https://github.com/npm/npm/issues/12196
