### ISSUE TITLE
Incorrect stdin(4) detection in `gitlab-multi-runner-ci`

### ISSUE THREAD

**Issue by evilebottnawi** [wooorm/remark#176]
run throw `gulp-remark` in gitlab-multi-runner-ci i got error:

```shell
[16:21:18] Error: remark does not accept both files and stdin
    at Ware.stdin (/path/to/node_modules/remark/lib/cli/file-set-pipeline/stdin.js:50:19)
    at Ware.<anonymous> (/path/to/node_modules/wrap-fn/index.js:45:19)
    at next (/path/to/node_modules/ware/lib/index.js:85:20)
    at /path/to/node_modules/wrap-fn/index.js:121:18
    at next (/path/to/node_modules/remark/lib/cli/file-set-pipeline/file-system.js:44:13)
    at /path/to/node_modules/remark/lib/cli/ignore.js:185:13
    at /path/to/node_modules/vfile-find-up/index.js:207:17
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by wooorm** [comment]
This question is better asked over at [gulp-remark](https://github.com/denysdovhan/gulp-remark). Plus, you should provide more information, such as version numbers for gulp, gulp-remark, npm, and node, and post your gulp file.

**Comment by evilebottnawi** [comment]
@wooorm run from cli without gulp give same error, node 5.10.1, npm 3.8.3

**Comment by wooorm** [comment]
OK, thanks. How do you run the CLI?

**Comment by evilebottnawi** [comment]
@wooorm 
```shell
remark . --quiet --frail
```

**Comment by evilebottnawi** [comment]
@wooorm gitlab ci create docker container without TTY, maybe problem in this?

**Comment by wooorm** [comment]
Something close to that at least; for this error to show up, the [`0` descriptor must also be a FIFO](https://github.com/wooorm/remark/blob/master/lib/cli/file-set-pipeline/stdin.js#L30), that was added in GH-118.

Could you run the following code in the CI?

```js
var isFIFO;

try { isFIFO = fs.fstatSync(0).isFIFO(); } catch (e) { console.log('e: ', e); }

console.log(isFIFO);
```

And show me the results?

Also: could you run `DEBUG="*" remark . --quiet --frail`, and show me those results?

**Comment by evilebottnawi** [comment]
@wooorm 
Script output:
```shell
$ node test.js
true
```

**Comment by evilebottnawi** [comment]
@wooorm 
run `DEBUG="*" remark . --quiet --frail`:
```shell
$ DEBUG="*" node_modules/remark/bin/remark . --quiet --frail
Fri, 22 Apr 2016 09:32:06 GMT remark:cli:ignore Constructing ignore for `/tmp/wordpress/src/wp-content/themes/insteria`
Fri, 22 Apr 2016 09:32:06 GMT remark:cli:file-set-pipeline:stdin Checking stdin
Fri, 22 Apr 2016 09:32:06 GMT remark:cli:file-set-pipeline:stdin Ignoring stdin
Error: remark does not accept both files and stdin
    at Ware.stdin (/path/to/node_modules/remark/lib/cli/file-set-pipeline/stdin.js:50:19)
    at Ware.<anonymous> (/path/to/node_modules/wrap-fn/index.js:45:19)
    at next (/path/to/node_modules/ware/lib/index.js:85:20)
    at /path/to/node_modules/wrap-fn/index.js:121:18
    at /path/to/node_modules/remark/lib/cli/file-set-pipeline/file-system.js:50:13
    at /path/to/node_modules/remark/lib/cli/finder.js:149:13
    at /path/to/node_modules/vfile-find-down/index.js:285:9
    at next (/path/to/node_modules/vfile-find-down/index.js:242:13)
    at /path/to/node_modules/vfile-find-down/index.js:249:13
    at /path/to/node_modules/vfile-find-down/index.js:208:21

ERROR: Build failed: exit code 1
```

**Comment by wooorm** [comment]
OK, one more, what does this produce? Sorry for the Qs.

```js
var isTTY = process.stdin.isTTY;
var isFIFO;

try { isFIFO = fs.fstatSync(0).isFIFO(); } catch (e) { /* Empty */ }

var a = isTTY === true || isFIFO === true;
var b = !isTTY && !isFIFO;

console.log('tty: ', a);
console.log('in: ', b);
```

**Comment by evilebottnawi** [comment]
@wooorm 
```shell
$ node test.js
tty:  true
in:  false
```

**Comment by evilebottnawi** [comment]
@wooorm Thanks! :+1:

**Comment by wooorm** [comment]
No problem, thank you for reporting 👌

**Comment by evilebottnawi** [comment]
@wooorm please publish new version on npm

**Comment by wooorm** [comment]
[Check again](https://www.npmjs.com/package/remark)

**Comment by evilebottnawi** [comment]
@wooorm good :smile:
