### ISSUE TITLE
after upgrade to `3.0.0` version i get error on node 4

### ISSUE THREAD

**Issue by evilebottnawi** [wooorm/remark#238]
```shell
[lint:remark ] Error: Cannot find module 'xtend'
[lint:remark ]     at Function.Module._resolveFilename (module.js:325:15)
[lint:remark ]     at Function.Module._load (module.js:276:25)
[lint:remark ]     at Module.require (module.js:353:17)
[lint:remark ]     at require (internal/module.js:12:17)
[lint:remark ]     at Object.<anonymous> (/path/to/node_modules/remark-cli/node_modules/unified-args/node_modules/unified-engine/lib/configuration.js:11:13)
[lint:remark ]     at Module._compile (module.js:409:26)
[lint:remark ]     at Object.Module._extensions..js (module.js:416:10)
[lint:remark ]     at Module.load (module.js:343:32)
[lint:remark ]     at Function.Module._load (module.js:300:12)
[lint:remark ]     at Module.require (module.js:353:17)
```

**Comment by wooorm** [comment]
What are you using, what linter is this?

**Comment by evilebottnawi** [comment]
@wooorm `remark-cli`

**Comment by evilebottnawi** [comment]
@wooorm `remark . -f -i .gitignore -q`

**Comment by wooorm** [comment]
Oh you’re right, found it! Reason is [`xtend` is in dev-depenendencies](https://github.com/unifiedjs/unified-engine/blob/0e5029dd250a52d3490ef2c93c2449ff995b084f/package.json#L53), and should be in dependencies.

I’ll have a fix in a minute.
