### ISSUE TITLE
Error When Piping to Stdin

### ISSUE THREAD

**Issue by sbdchd** [wooorm/remark#239]
I used to use the following setup:

```
cat README.md | remark
# spits out formatted markdown
```

However, now this setup produces the following error:

```
<stdin>
  1:1  error  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at resolve (path.js:1148:7)
    at FindUp.load (/usr/local/lib/node_modules/remark-cli/node_modules/unified-engine/lib/find-up.js:61:14)
    at Config.load (/usr/local/lib/node_modules/remark-cli/node_modules/unified-engine/lib/configuration.js:71:15)
    at configure (/usr/local/lib/node_modules/remark-cli/node_modules/unified-engine/lib/file-pipeline/configure.js:20:10)
    at wrapped (/usr/local/lib/node_modules/remark-cli/node_modules/trough/index.js:128:19)
    at next (/usr/local/lib/node_modules/remark-cli/node_modules/trough/index.js:81:24)
    at done (/usr/local/lib/node_modules/remark-cli/node_modules/trough/index.js:163:12)
    at read (/usr/local/lib/node_modules/remark-cli/node_modules/unified-engine/lib/file-pipeline/read.js:19:5)
    at wrapped (/usr/local/lib/node_modules/remark-cli/node_modules/trough/index.js:128:19)

✖ 1 error
```

**Comment by wooorm** [comment]
Ah, sorry about that!

Could you run with `DEBUG="*" cat README.md | remark` and post the results?

**Comment by sbdchd** [comment]
Sure thing! This is what `remark` produced:
```
bash-4.4$ DEBUG="*" cat README.md | remark
<stdin>
  1:1  error  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at resolve (path.js:1148:7)
    at FindUp.load (/usr/local/lib/node_modules/remark-cli/node_modules/unified-engine/lib/find-up.js:61:14)
    at Config.load (/usr/local/lib/node_modules/remark-cli/node_modules/unified-engine/lib/configuration.js:71:15)
    at configure (/usr/local/lib/node_modules/remark-cli/node_modules/unified-engine/lib/file-pipeline/configure.js:20:10)
    at wrapped (/usr/local/lib/node_modules/remark-cli/node_modules/trough/index.js:128:19)
    at next (/usr/local/lib/node_modules/remark-cli/node_modules/trough/index.js:81:24)
    at done (/usr/local/lib/node_modules/remark-cli/node_modules/trough/index.js:163:12)
    at read (/usr/local/lib/node_modules/remark-cli/node_modules/unified-engine/lib/file-pipeline/read.js:19:5)
    at wrapped (/usr/local/lib/node_modules/remark-cli/node_modules/trough/index.js:128:19)

✖ 1 error
```

**Comment by wooorm** [comment]
Oh gah, I think the debug env variable should be in the remark part, `cat README.md | DEBUG="*" remark` or something, sorry.

**Comment by sbdchd** [comment]
Here you go:
```
bash-4.4$ cat README.md | DEBUG="*" remark
  unified-engine:configuration Looking for `.remarkrc,.remarkrc.js,.remarkrc.yml,.remarkrc.yaml` configuration files +0ms
  unified-engine:configuration Looking for `remarkConfig` fields in `package.json` files +2ms
  unified-engine:file-set-pipeline:stdin Reading from `streamIn` +3ms
  unified-engine:file-set-pipeline:stdin Read from `streamIn` +6ms
  unified-engine:file-pipeline:read Not reading file `undefined` with contents +2ms
  unified-engine:file-pipeline:queue Queueing `undefined` +4ms
  unified-engine:file-pipeline:queue Flushing: all files can be flushed +0ms
  unified-engine:file-pipeline:stringify Not compiling failed document +1ms
  unified-engine:file-pipeline:copy Not copying +0ms
  unified-engine:file-pipeline:stdout Ignoring writing to `streamOut` +0ms
  unified-engine:file-pipeline:file-system Ignoring writing to file-system +0ms
<stdin>
  1:1  error  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at resolve (path.js:1148:7)
    at FindUp.load (/usr/local/lib/node_modules/remark-cli/node_modules/unified-engine/lib/find-up.js:61:14)
    at Config.load (/usr/local/lib/node_modules/remark-cli/node_modules/unified-engine/lib/configuration.js:71:15)
    at configure (/usr/local/lib/node_modules/remark-cli/node_modules/unified-engine/lib/file-pipeline/configure.js:20:10)
    at wrapped (/usr/local/lib/node_modules/remark-cli/node_modules/trough/index.js:128:19)
    at next (/usr/local/lib/node_modules/remark-cli/node_modules/trough/index.js:81:24)
    at done (/usr/local/lib/node_modules/remark-cli/node_modules/trough/index.js:163:12)
    at read (/usr/local/lib/node_modules/remark-cli/node_modules/unified-engine/lib/file-pipeline/read.js:19:5)
    at wrapped (/usr/local/lib/node_modules/remark-cli/node_modules/trough/index.js:128:19)

✖ 1 error
```

**Comment by wooorm** [comment]
Hmm, could try this for me? Replace L71 in `unified-engine/lib/configuration.js`:

```diff
  var self = this;

- self.findUp.load(filePath, done);
+ if (filePath) {
+   self.findUp.load(filePath, done);
+ } else {
+   done();
+ }

  function done(err, res) {

**Comment by sbdchd** [comment]
That seemed to do the trick!

Thanks.

**Comment by wooorm** [comment]
Alright, thanks. I’ll push a fix in a minute!
