### ISSUE TITLE
TypeError: Path must be a string 

### ISSUE THREAD

**Issue by samumist** [wooorm/remark#241]
Thanks for the amazing plugin.

I use remark with [vim-autoformat](https://github.com/Chiel92/vim-autoformat) to format markdown files. Remark stops working with the following error messages when used within VIM (via the auto-format shortcut).

```
"hello.md" 7L, 62C
"hello.md" 4L, 59C written
Formatter remark_markdown has errors: <stdin>
  1:1  error  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at posix.resolve (path.js:426:5)
    at FindUp.load (/Users/sam/.nvm/versions/node/v4.7.3/lib/node_modules/remark-cli/node_modules/unified-engine/lib/find-up.js:61:14)
    at Config.load (/Users/sam/.nvm/versions/node/v4.7.3/lib/node_modules/remark-cli/node_modules/unified-engine/lib/configuration.js:71:15)
    at configure (/Users/sam/.nvm/versions/node/v4.7.3/lib/node_modules/remark-cli/node_modules/unified-engine/lib/file-pipeline/configure.js:20:10)
    at wrapped (/Users/sam/.nvm/versions/node/v4.7.3/lib/node_modules/remark-cli/node_modules/trough/index.js:128:19)
    at next (/Users/sam/.nvm/versions/node/v4.7.3/lib/node_modules/remark-cli/node_modules/trough/index.js:81:24)
    at done (/Users/sam/.nvm/versions/node/v4.7.3/lib/node_modules/remark-cli/node_modules/trough/index.js:163:12)
    at read (/Users/sam/.nvm/versions/node/v4.7.3/lib/node_modules/remark-cli/node_modules/unified-engine/lib/file-pipeline/read.js:19:5)
    at wrapped (/Users/sam/.nvm/versions/node/v4.7.3/lib/node_modules/remark-cli/node_modules/trough/index.js:128:19)
✖ 1 error
 Skipping.
Failing config: 'remark --silent --no-color'
Definition in 'g:formatdef_remark_markdown' was unsuccessful.
No format definitions were successful.
"message.txt" [readonly] 864L, 30984C
```

Remark works fine when used on the command-line. I'm not sure if this is a problem of remark or vim-autoformat.

**Environment: **
remark-cli: 3.0
remark: 7.0.0
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar  1 2017 14:34:19) MacOS X (unix) version

**Comment by wooorm** [comment]
Hi @samumist!

This was caused by a bug which was solved yesterday. To fix, update your dependencies: something like `npm update` but I’m not sure how vim-autoformat installs dependencies.

Related: GH-239.

**Comment by samumist** [comment]
Many thanks.

**Comment by wooorm** [comment]
👍
