### ISSUE TITLE
Plugin lookup path based on absolute path of config file?

### ISSUE THREAD

**Issue by thorncp** [wooorm/remark#257]
I'm trying to run remark in a directory outside of my project directory. Specifically, I want to lint a file in a temporary directory, isolated from the rest of the world. If I use the config path that lives in the project, I get the linting behavior I expect. If the same config file lives in the temporary directory, remark errors saying it cannot find the `remark-preset-lint-recommended` plugin.

Is this expected? Am I doing something wrong?

#### from package.json:

```json
    "remark-cli": "^3.0.1",
    "remark-lint": "^6.0.0",
    "remark-preset-lint-recommended": "^2.0.0",
```

#### .remarkrc:

```
{
  "plugins": ["remark-preset-lint-recommended"]
}
```

#### foo.md:

```md
* Hello

[World][]
```

#### Example with config file in the project:

```text
% pwd
/tmp/remark

% ~/code/hound/linters/node_modules/remark-cli/cli.js -r ~/code/hound/linters/config/remarkrc foo.md
-   Hello

[World][]
foo.md
       1:3  warning  Incorrect list-item indent: add 2 spaces  list-item-indent         remark-lint
  3:1-3:10  warning  Found reference to undefined definition   no-undefined-references  remark-lint

⚠ 2 warnings
```

#### Example with local config file:

```text
% cp ~/code/hound/linters/config/remarkrc .remarkrc

% ~/code/hound/linters/node_modules/remark-cli/cli.js -r .remarkrc foo.md
foo.md
  1:1  error  Error: Could not find module `remark-preset-lint-recommended`
    at addModule (/Users/chris/code/hound/linters/node_modules/unified-engine/lib/configuration.js:232:35)
    at use (/Users/chris/code/hound/linters/node_modules/unified-engine/lib/configuration.js:202:7)
    at addEach (/Users/chris/code/hound/linters/node_modules/unified-engine/lib/configuration.js:187:9)
    at addPreset (/Users/chris/code/hound/linters/node_modules/unified-engine/lib/configuration.js:165:9)
    at merge (/Users/chris/code/hound/linters/node_modules/unified-engine/lib/configuration.js:151:5)
    at Config.create (/Users/chris/code/hound/linters/node_modules/unified-engine/lib/configuration.js:106:5)
    at loadGiven (/Users/chris/code/hound/linters/node_modules/unified-engine/lib/find-up.js:83:18)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)

✖ 1 error
```

**Comment by wooorm** [comment]
Yes, that’s expected behaviour: plugins specified in a config file are loaded from that config file!

Note that the strings in `plugins` in config files are required, so they can also be absolute or relative paths. Thus, a `.remarkrc` could look like this:

```js
{
  "plugins": ["/foo/bar/baz/node_modules/remark-preset-lint-recommended"]
}
```

**Comment by wooorm** [comment]
@thorncp Did my comment above help?

**Comment by thorncp** [comment]
@wooorm Yes it did, thanks. I haven't been able to get back to what I'm working on with this new knowledge yet, but I think I've got enough info to move forward.

**Comment by wooorm** [comment]
Great to hear! Cheers, Chris!
