### ISSUE TITLE
Ignore not being used on ignore file itself

### ISSUE THREAD

**Issue by niftylettuce** [wooorm/remark#292]
If you run `remark ignore.md -qfo` with a `.remarkignore` with one line inside of `ignore.md` it will not ignore that file, it will still lint and fix it.

**Comment by niftylettuce** [comment]
Also, when combining ignores from `.remarkignore` along with `lint-staged`, it hangs:

![kapture 2017-09-02 at 0 53 43](https://user-images.githubusercontent.com/523141/29993055-48f150ce-8f79-11e7-9225-72788f1b13fa.gif)

Related (since we currently can't specify ignores with `lint-staged`):
* https://github.com/okonet/lint-staged/pull/188#issuecomment-309735299
* https://github.com/okonet/lint-staged/issues/204
* https://github.com/okonet/lint-staged/issues/123

**Comment by wooorm** [comment]
👋

I don’t quite get your first question. Could you provide a) exactly how you’re running remark, b) the contents of `ignore.md`, and c) the contents of `.remarkignore`?

I’m not sure about your `lint-staged` question either. `lint-staged` seems to pass in files that are ignored by your `.remarkignore`, and remark-cli will warn for that because it’s not allowed! I’m not sure why it hangs though. Could you run `lint-staged` with something to produce more debugging info?

**Comment by wooorm** [comment]
@niftylettuce Friendly ping!

**Comment by niftylettuce** [comment]
@wooorm basically this is how to reproduce `remark . -qfo`:

```sh
λ ~/Public/lad/template/ master* node_modules/.bin/remark . -qfo
Error: No input
    at stdin (/Users/nexus/Public/lad/template/node_modules/unified-engine/lib/file-set-pipeline/stdin.js:30:10)
    at wrapped (/Users/nexus/Public/lad/template/node_modules/trough/index.js:93:19)
    at next (/Users/nexus/Public/lad/template/node_modules/trough/index.js:56:24)
    at done (/Users/nexus/Public/lad/template/node_modules/trough/index.js:124:12)
    at found (/Users/nexus/Public/lad/template/node_modules/unified-engine/lib/file-set-pipeline/file-system.js:53:5)
    at done (/Users/nexus/Public/lad/template/node_modules/unified-engine/lib/finder.js:32:7)
    at done (/Users/nexus/Public/lad/template/node_modules/unified-engine/lib/finder.js:95:7)
    at one (/Users/nexus/Public/lad/template/node_modules/unified-engine/lib/finder.js:192:9)
    at one (/Users/nexus/Public/lad/template/node_modules/unified-engine/lib/finder.js:192:9)
    at one (/Users/nexus/Public/lad/template/node_modules/unified-engine/lib/finder.js:192:9)
```

It should be like `eslint` and `xo`:

```sh
λ ~/Dropbox/test/ xo .
λ ~/Dropbox/test/ eslint .
λ ~/Dropbox/test/
```

As you can see - no output / error thrown even though no files detected!

**Comment by wooorm** [comment]
Thanks but that's a response to https://github.com/wooorm/remark/issues/294

Could you answer https://github.com/wooorm/remark/issues/292#issuecomment-32673673?

**Comment by wooorm** [comment]
Closing this due to not being actionable for us currently. Feel free to respond and I’ll re-open.

**Comment by SiarheiBobryk** [comment]
About "remark-lint" and "lintstage".

Thanks to @wooorm I've managed to fix the issue by separating the script from the Prettier script.

Here is the working example:

`package.json`:

```json
"scripts": {
  "format:fix": "prettier . --write",
  "format": "prettier . --check",
  "lint:md:fix": "remark . --quiet --frail --output",
  "lint:md": "remark . --quiet --frail"
},
```

`lintstagedrc`:

```json
{
  "*.(js|ts|tsx)": ["yarn format", "yarn lint"],
  "*.(html|json|yaml|xml)": "yarn format",
  "*.(md)": "yarn lint:md"
}
```

cc @niftylettuce
