### ISSUE TITLE
CLI should not throw error when no files available to lint

### ISSUE THREAD

**Issue by niftylettuce** [wooorm/remark#294]
I think this should be similar to eslint and xo, where if there are no files to lint then it does not throw an error, it just is completely silent on output.

```log
λ ~/Public/lad/template/ master* node_modules/.bin/remark . -qfo
Error: No input
    at stdin (/Users/niftylettuce/Public/lad/template/node_modules/unified-engine/lib/file-set-pipeline/stdin.js:30:10)
    at wrapped (/Users/niftylettuce/Public/lad/template/node_modules/trough/index.js:93:19)
    at next (/Users/niftylettuce/Public/lad/template/node_modules/trough/index.js:56:24)
    at done (/Users/niftylettuce/Public/lad/template/node_modules/trough/index.js:124:12)
    at found (/Users/niftylettuce/Public/lad/template/node_modules/unified-engine/lib/file-set-pipeline/file-system.js:53:5)
    at done (/Users/niftylettuce/Public/lad/template/node_modules/unified-engine/lib/finder.js:32:7)
    at done (/Users/niftylettuce/Public/lad/template/node_modules/unified-engine/lib/finder.js:95:7)
    at one (/Users/niftylettuce/Public/lad/template/node_modules/unified-engine/lib/finder.js:192:9)
    at one (/Users/niftylettuce/Public/lad/template/node_modules/unified-engine/lib/finder.js:192:9)
    at one (/Users/niftylettuce/Public/lad/template/node_modules/unified-engine/lib/finder.js:192:9)
```

**Comment by wooorm** [comment]
Should happen in `unified-engine`! See unifiedjs/unified-engine#29 for more info.
